[package]
name = "mbr-ssg"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
description = "Static site generator for mbr, the markdown browser"
homepage.workspace = true
repository.workspace = true
documentation.workspace = true
readme = "../../README.md"

[lib]
name = "mbr_ssg"
bench = false

[dependencies]
mbr-core.workspace = true

futures.workspace = true
pagefind.workspace = true
papaya.workspace = true
percent-encoding.workspace = true
rayon.workspace = true
scraper.workspace = true
serde_json.workspace = true
tera.workspace = true
tokio.workspace = true
tracing.workspace = true
walkdir.workspace = true

[dev-dependencies]
proptest.workspace = true
tempfile.workspace = true
